#!/bin/bash

BLACKLIST="$(afdns-blacklist-file)"

if afdns-host-added "${1}";
then
    exit 0
fi

if [ "${1}" = "" ];
then
    exit 1
fi

RULE="$(afdns-host-rule ${1})"
echo "${RULE}" >> ${BLACKLIST}

afdns-restart
