#!/bin/bash -e

if afdns-host-added "${1}";
then
    exit 0
fi

if [ "${1}" = "" ];
then
    exit 1
fi

RULE="$(afdns-host-get-rule ${1})"
echo "${RULE}" >> ${AFDNS_BLACKLIST_MANUAL}

service bind9 restart
