#!/bin/bash

# Start cron service which is not started automatically.
service cron start

# Initialize custom blacklist database.
afdns-blacklist-initialize

# Update automatic blacklist database.
afdns-update

# Keep container running.
bash
