#!/bin/bash -e

# This scipt updates automtic blacklist from http://hosts-file.net/.

# Hosts file URL.
HOSTS_URL="http://hosts-file.net/download/hosts.txt"

# Download the latest version of the hosts file.
/usr/bin/wget --quiet --output-document=${AFDNS_BLACKLIST_TEMPORARY} ${HOSTS_URL}

# Remove \r characters
sed -i 's/\r//' ${AFDNS_BLACKLIST_TEMPORARY}

# Initialize the blacklist with the template
cp ${AFDNS_BLACKLIST_TEMPLATE} ${AFDNS_BLACKLIST_AUTO}

# Perform the parsing.
/usr/bin/awk '
    /^127\.0\.0\.1\t/ {
        print $2" CNAME ."
    }
' ${AFDNS_BLACKLIST_TEMPORARY} >> ${AFDNS_BLACKLIST_AUTO}

# Restart the DNS server.
service bind9 restart

# Set default update source.
/bin/ln -fs /usr/bin/afdns-update-hph /usr/bin/afdns-update
