#!/bin/bash -e

# This scipt updates an automtic blacklist from https://github.com/StevenBlack/hosts.

# Hosts file URL.
HOSTS_URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

# Download the latest version of the hosts file.
/usr/bin/wget --quiet --output-document=${AFDNS_BLACKLIST_TEMPORARY} ${HOSTS_URL}

# Initialize the blacklist with the template.
cp ${AFDNS_BLACKLIST_TEMPLATE} ${AFDNS_BLACKLIST_AUTO}

# Perform the parsing.
/usr/bin/awk '
    /^0\.0\.0\.0 / {
        print $2" CNAME ."
    }
' ${AFDNS_BLACKLIST_TEMPORARY} >> ${AFDNS_BLACKLIST_AUTO}

# Restart the DNS server.
service bind9 restart

# Set default update source.
/bin/ln -fs /usr/bin/afdns-update-ahf /usr/bin/afdns-update
