#!/bin/bash -e

# Install required software.
apt-get update
apt-get install --yes \
    bind9 \
    cron \
    wget \

# Install bind configuration files.
cp /var/lib/afdns/* /etc/bind/

# Initialize the manual blacklist.
cp ${AFDNS_BLACKLIST_TEMPLATE} ${AFDNS_BLACKLIST_MANUAL}

# Add a cron job which will update an automatic blacklist.
cp /usr/bin/afdns-update /etc/cron.daily/
